version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}

  frontend:
    build: ./frontend
    ports:
      - '3001:3000'

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest_next_chat_app
    ports:
      - '5432:5432'
